spring.application.name=api-gateway


server.port=3333

# Eureka Server
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# Welcome Service Route
spring.cloud.gateway.server.webflux.routes[0].id=welcome-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://welcome-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/welcome/** 

# greet service
spring.cloud.gateway.server.webflux.routes[1].id=greet-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://greet-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/greet/**

