spring.application.name=cloud-config-server



server.port=9093

# Spring Cloud Config Server
spring.cloud.config.server.git.uri=https://github.com/Avnish-Roy/configuration-properties-ms1.git
spring.cloud.config.server.git.clone-on-start=true

management.security.enabled=false
