
spring.application.name=welcome-service

server.port=8082

spring.boot.admin.client.url=http://localhost:1111

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.management.endpoints.web.exposure.include=*
spring.management.endpoint.health.show-details=always

